#pragma once

#include <tuple>
#include <vector>


const std::vector<std::pair<std::string, std::vector<std::string>>> fileList =
{
  { "Armitems.256"
  , { "Armitems.pl8"
    , "Peasant.pl8"
    , "System.pl8"
    , "Troop1.pl8"
    , "Trp_ar_b.pl8"
    , "Trp_ar_k.pl8"
    , "Trp_ar_p.pl8"
    , "Trp_ar_r.pl8"
    , "Trp_ar_y.pl8"
    , "Trp_kn_b.pl8"
    , "Trp_kn_k.pl8"
    , "Trp_kn_p.pl8"
    , "Trp_kn_r.pl8"
    , "Trp_kn_y.pl8"
    , "Trp_ma_b.pl8"
    , "Trp_ma_k.pl8"
    , "Trp_ma_p.pl8"
    , "Trp_ma_r.pl8"
    , "Trp_ma_y.pl8"
    , "Trp_pi_b.pl8"
    , "Trp_pi_k.pl8"
    , "Trp_pi_p.pl8"
    , "Trp_pi_r.pl8"
    , "Trp_pi_y.pl8"
    , "Trp_sw_b.pl8"
    , "Trp_sw_k.pl8"
    , "Trp_sw_p.pl8"
    , "Trp_sw_r.pl8"
    , "Trp_sw_y.pl8"
    , "Trp_xb_b.pl8"
    , "Trp_xb_k.pl8"
    , "Trp_xb_p.pl8"
    , "Trp_xb_r.pl8"
    , "Trp_xb_y.pl8"
    }
  },
  {"Armoury.256",
    { "Arm_bow.pl8"
    , "Arm_cros.pl8"
    , "Arm_it_b.pl8"
    , "Arm_it_k.pl8"
    , "Arm_it_p.pl8"
    , "Arm_it_r.pl8"
    , "Arm_it_y.pl8"
    , "Arm_mace.pl8"
    , "Arm_mail.pl8"
    , "Armoury.pl8"
    , "Arm_pike.pl8"
    , "Arm_swor.pl8"
    , "Armtorch.pl8"
    }
  },
  {"Base01.256",
    {"Backgrnd.pl8"
    , "Base1a.pl8"
    , "Base1b.pl8"
    , "Base1c.pl8"
    , "Base1d.pl8"
    , "Base2a.pl8"
    , "Base2b.pl8"
    , "Base2c.pl8"
    , "Base2d.pl8"
    , "Castle1a.pl8"
    , "Castle1b.pl8"
    , "Castle1c.pl8"
    , "Castle1d.pl8"
    , "Castle2a.pl8"
    , "Castle2b.pl8"
    , "Castle2c.pl8"
    , "Castle2d.pl8"
    , "Castle.pl8"
    , "Flags1a.pl8"
    , "Flags1b.pl8"
    , "Flags1c.pl8"
    , "Flags1d.pl8"
    , "Flags2a.pl8"
    , "Graphs.pl8"
    , "Hearth.pl8"
    , "Icon_tmp.pl8"
    , "Iconvill.pl8"
    , "Map01.pl8"
    , "Map02.pl8"
    , "Map03.pl8"
    , "Map04.pl8"
    , "Map05.pl8"
    , "Map06.pl8"
    , "Misc_cty.pl8"
    , "Mouse.pl8"
    , "Mtns1a.pl8"
    , "Mtns1b.pl8"
    , "Mtns1c.pl8"
    , "Mtns1d.pl8"
    , "Mtns2a.pl8"
    , "Mtns2b.pl8"
    , "Mtns2c.pl8"
    , "Mtns2d.pl8"
    , "Panels.pl8"
    , "Roads1a.pl8"
    , "Roads1b.pl8"
    , "Roads1c.pl8"
    , "Roads1d.pl8"
    , "Roads2a.pl8"
    , "Roads2b.pl8"
    , "Roads2c.pl8"
    , "Roads2d.pl8"
    , "Sgeplans.pl8"
    , "Smithy.pl8"
    , "Title.pl8"
    , "Village3.pl8"
    , "Village4.pl8"
    , "Village.pl8"
    , "Villani1.pl8"
    , "Villani2.pl8"
    , "Villbord.pl8"
    , "Vill.pl8"
    , "Villtops.pl8"
    }
  },
  {"Base1a.256",
    { "Torches.pl8"
    , "Town1a.pl8"
    , "Town1b.pl8"
    , "Town1c.pl8"
    , "Town1d.pl8"
    , "Town2a.pl8"
    , "Town2b.pl8"
    , "Town2c.pl8"
    , "Town2d.pl8"
    }
  },
  {"Cas_back.256",
    { "Cas_back.pl8"
    , "Cas_bits.pl8"
    , "Caspics.pl8"
    }
  },
  {"Custom.256",
    { "Custom.pl8"
    , "Misc_sel.pl8"
    }
  },
  {"Gateway.256",
    { "Gateway.pl8"
    , "Panels2.pl8"
    , "System2.pl8"
    }
  },
  {"Grtnoble.256",
    { "Flags.pl8"
    , "Grtnoble.pl8"
    , "Stnfield.pl8"
    }
  },
  {"Lords2.256",
    { "Faces.pl8"
    , "Fnt_8.pl8"
    , "Fntl2_14.pl8"
    , "Fntl2_22.pl8"
    , "Fntl2_9.pl8"
    , "Font_10.pl8"
    , "Font3c2.pl8"
    , "Font_c2.pl8"
    , "Lords2.pl8"
    }
  },
  {"Merchant.256",
    { "Icontrad.pl8"
    , "Merchant.pl8"
    }
  },
  {"Sprite01.256",
    { "Batfield.pl8"
    , "Batlfix2.pl8"
    , "Sprite02.pl8"
    , "T2_spri.pl8"
    }
  },
  {"Sprite1a.256",
    { "Sprite1a.pl8"
    , "Sprite1b.pl8"
    , "Sprite2a.pl8"
    , "Sprite2b.pl8"
    }
  },
  {"Start.256", {"Start.pl8"}},
  {"T32_bat1.256",
    { "A2b_arch.pl8"
    , "A2b_cros.pl8"
    , "A2b_knig.pl8"
    , "A2b_mace.pl8"
    , "A2b_peas.pl8"
    , "A2b_pike.pl8"
    , "A2b_psnt.pl8"
    , "A2b_swor.pl8"
    , "A2g_arch.pl8"
    , "A2g_cros.pl8"
    , "A2g_knig.pl8"
    , "A2g_mace.pl8"
    , "A2g_pike.pl8"
    , "A2g_psnt.pl8"
    , "A2g_swor.pl8"
    , "A2_horse.pl8"
    , "A2k_arch.pl8"
    , "A2k_cros.pl8"
    , "A2k_knig.pl8"
    , "A2k_mace.pl8"
    , "A2k_pike.pl8"
    , "A2k_psnt.pl8"
    , "A2k_swor.pl8"
    , "A2_miss.pl8"
    , "A2p_arch.pl8"
    , "A2p_cros.pl8"
    , "A2p_knig.pl8"
    , "A2p_mace.pl8"
    , "A2p_pike.pl8"
    , "A2p_psnt.pl8"
    , "A2p_swor.pl8"
    , "A2r_arch.pl8"
    , "A2r_cros.pl8"
    , "A2r_knig.pl8"
    , "A2r_mace.pl8"
    , "A2r_peas.pl8"
    , "A2r_pike.pl8"
    , "A2r_psnt.pl8"
    , "A2r_swor.pl8"
    , "A2w_arch.pl8"
    , "A2w_cros.pl8"
    , "A2w_knig.pl8"
    , "A2w_mace.pl8"
    , "A2w_pike.pl8"
    , "A2w_psnt.pl8"
    , "A2w_swor.pl8"
    , "A2y_arch.pl8"
    , "A2y_cros.pl8"
    , "A2y_knig.pl8"
    , "A2y_mace.pl8"
    , "A2y_pike.pl8"
    , "A2y_psnt.pl8"
    , "A2y_swor.pl8"
    , "A3b_arch.pl8"
    , "A3b_cros.pl8"
    , "A3b_knig.pl8"
    , "A3b_mace.pl8"
    , "A3b_pike.pl8"
    , "A3b_psnt.pl8"
    , "A3b_swor.pl8"
    , "A3_horse.pl8"
    , "A3k_arch.pl8"
    , "A3k_cros.pl8"
    , "A3k_knig.pl8"
    , "A3k_mace.pl8"
    , "A3k_pike.pl8"
    , "A3k_psnt.pl8"
    , "A3k_swor.pl8"
    , "A3p_arch.pl8"
    , "A3p_cros.pl8"
    , "A3p_knig.pl8"
    , "A3p_mace.pl8"
    , "A3p_pike.pl8"
    , "A3p_psnt.pl8"
    , "A3p_swor.pl8"
    , "A3r_arch.pl8"
    , "A3r_cros.pl8"
    , "A3r_knig.pl8"
    , "A3r_mace.pl8"
    , "A3r_pike.pl8"
    , "A3r_psnt.pl8"
    , "A3r_swor.pl8"
    , "A3w_arch.pl8"
    , "A3w_cros.pl8"
    , "A3w_knig.pl8"
    , "A3w_mace.pl8"
    , "A3w_pike.pl8"
    , "A3w_psnt.pl8"
    , "A3w_swor.pl8"
    , "A3y_arch.pl8"
    , "A3y_cros.pl8"
    , "A3y_knig.pl8"
    , "A3y_mace.pl8"
    , "A3y_pike.pl8"
    , "A3y_psnt.pl8"
    , "A3y_swor.pl8"
    , "Catarm1.pl8"
    , "Catarm2.pl8"
    , "Engine.pl8"
    , "Misc_bat.pl8"
    , "Pikemen.pl8"
    , "T16_bat1.pl8"
    , "T2_bat1.pl8"
    , "T32_bat1.pl8"
    }
  },
  {"T32_stn1.256",
    { "T2_stn1.pl8"
    , "T2_stn2.pl8"
    , "T2_wod1.pl8"
    , "T2_wod2.pl8"
    , "T32_bat.pl8"
    , "T32_stn1.pl8"
    , "T32_stn2.pl8"
    , "T32_stna.pl8"
    , "T32_wod1.pl8"
    , "T32_wod2.pl8"
    }
  },
  {"Treasury.256",
    {"Crossbow.pl8"
    , "Treasury.pl8"
    }
  }
};


const std::vector<std::pair<std::string, std::vector<std::string>>> fileList2 =
{
  {"T32_stn1.256",
    { "T32_stn1.pl8"
    }
  }
};
