name:                lords-of-realms2-parser
version:             0.1.0.0
#synopsis:
homepage:            https://github.com/githubuser/lord-of-realms2-parser#readme
license:             MIT
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

description: >
    Please see the README on Github at 
    <https://github.com/githubuser/lord-of-realms2-parser#readme>

flags:
  pedantic:
    description: Pass additional warning flags and -Werror to GHC.
    default: True
    manual: True

dependencies:
  - base >= 4.7 && < 5
  - cereal
  - vector
  - bytestring
  - JuicyPixels

executables:
  lords-of-realms2-parser:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wimplicit-prelude
      - -Wmissing-import-lists
